config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :exersizes, only: [:index, :create]
      get 'exersizes/body_parts', to: 'exersizes#body_parts'
      resources :users, only: [:create]
      resources :trainings, only: [:index, :create, :update, :destroy, :show] do
        resources :workout_sets, only: [:index, :create, :update, :destroy]
      end
      post 'login', to: 'sessions#create'
    end
  end
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  has_many :workout_sets

  scope :for_user, ->(user) { where(user_id: user.id) }
end

app/controllers/api/v1/trainings_controller.rb
module Api
  module V1
    class TrainingsController < ApplicationController
      before_action :authenticate_request

      def index
        trainings = Training.for_user current_user

        render json: { trainings: trainings.map{ |training| ::Api::V1::TrainingSerializer.new(training) } }, status: :ok
      end

      def create
        training = Training.new(user_id: current_user.id)
        if training.save
          render json: { training: ::Api::V1::TrainingSerializer.new(training) }, status: :created
        end
      end

      def show
        training = Training.for_user(current_user).find(params[:id])

        if training
          render json: { training: ::Api::V1::TrainingSerializer.new(training) }, status: :ok
        end
      end

      def update
        training = Training.for_user(current_user).find(params[:id])

        if training.update(training_params)
          render json: { training: ::Api::V1::TrainingSerializer.new(training) }, status: :ok
        end
      end

      def destroy
        training = Training.for_user(current_user).find(params[:id])
        if training.destroy
          render json: {}, status: :no_content
        end
      end

      private

      def training_params
        params.require(:training).permit(:description)
      end
    end
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  before_action :set_training, only: [:show, :edit, :update, :destroy]
  before_action :set_training_permission, only: [:permission_policy, :permission]

  def index
    @trainings = if current_user.has_role_admin?
      Training.all.paginate(page: params[:page], per_page:10) # paging
    else
      Training.for_current_user(current_user).paginate(page: params[:page], per_page:10)
    end
  end

  def show
  end

  def new
    @training = Training.new
  end

  def edit
  end

  def create
    @training = Training.new(trainee_id: current_user.id, trainer_id: current_user.id)
    respond_to do |format|
      if @training.save
        format.html { redirect_to edit_training_path(@training.id), notice: 'Тренировка успешно начата' }
        format.json { render :edit, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to edit_training_path(@training), notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    authorize_action_for @training

    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # permission UI page
  def permission_policy
    authorize_action_for @training
    @users = User.at_who session[:username]
  end

  # permission POST API
  def permission
    authorize_action_for @training

    ActiveRecord::Base.transaction do

      username = params[:username]
      training_id = params[:training_id]
      action = params[:control]
      role = case params[:role]
               when 'ROLE_ADMIN';    'admin'
               when 'ROLE_OWNER';    'owner'
               else 'none'
             end

      # get user
      user = User.find_by(username:username)

      # set role - add / remove
      case action
        when 'ADD'
          user.add_role(role, Training.find(training_id))
        when 'REMOVE'
          user.remove_role(role, Training.find(training_id))
        else nil
      end

    end

  end


  private

    def set_training
      @training = Training.find(params[:id])
    end

    def set_training_permission
      @training = Training.find(params[:training_id])
    end

    def training_params
      params.require(:training).permit(:comment, workout_sets_attributes: [:sets, :reps, :exersize_id])
    end

    def permission_params
      params.permit(:username, :role, :control)
    end
end

app/views/trainings/_current_workout_sets.html.erb
<% if workout_sets.any? %>
  <div id="workout-sets">
    <section class="mb-4">
      <h2 class="text-xl font-title mb-2">Подходы</h2>
      <ul class="space-y-2">
        <% workout_sets.each_with_index do |workout_set, index| %>
          <li class="p-4 bg-neutral-50 rounded-md shadow">
            <h3 class="text-lg"> Подход <%= index + 1 %> </h3>
            <p>Details about workout set 1</p>
            <%= workout_set.inspect %>
          </li>
        <% end %>
      </ul>
    </section>
  </div>
<% end %>

app/views/trainings/_form.html.erb
<%= form_for(training) do |tr| %>
    <%= tr.label 'Комментарий', class: ''  %>
    <%= tr.text_field :comment, class: '', autofocus: true, autocomplete: 'off', placeholder: 'Поделитесь впечатлениями как прошла ваша тренировка' %>
    <%= tr.submit %>
<% end %>
<br>
<%= render 'current_workout_sets', workout_sets: training.workout_sets %>
<%= render partial: "workout_sets/form", locals: {workout_set: @workout_set = WorkoutSet.new, training_id: training.id} %>

app/views/trainings/edit.html.erb
<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="space-y-2">
  <% @trainings.each do |training| %>
    <%= render partial: 'components/element', locals: { element: training } %>
  <% end %>
</ul>
<br>
<%= button_to 'Начать новую тренировку', trainings_path, class: 'bg-primary text-neutral-50 rounded-md py-2 w-full', method: 'post' %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>